#! /bin/sh

# Start Bar on initialization
$HOME/Scripts/poly &

# Initialize desktops
bspc monitor -d I II III IV V


# Colors
bspc config normal_border_color		"#928374"
bspc config active_border_color		"#458588"
bspc config focused_border_color	"#8ec07c"
bspc config presel_feedback_color	"#d65d0e"

bspc config border_width     5
bspc config window_gap      15
bspc config top_padding     50

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc paddingless_monocle         false

# Set lone tiled window to monocle mode
bspc config single_monocle	 true

# Controls
bspc config click_to_focus	 button1

# Rules
bspc rule -a Float state=floating
